packages:
  - "packages/**/*"
  - "apps/*"

catalog:
  hono: ^4.7.7
  tailwindcss: ^4.1.4
  "@tailwindcss/vite": ^4.1.4
  vite: ^6.3.2
  valibot: ^1.0.0

catalogs:
  react:
    "react": ^19.0.0
    "react-dom": ^19.0.0
    "@types/react": ^19.0.10
    "@types/react-dom": ^19.0.4
