name: Main CI

on:
  push:
    branches:
      - main

jobs:
  web:
    name: Web CI
    runs-on: ubuntu-latest

    environment: Production

    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Checks
        run: pnpm turbo lint build --filter=@tau/app

      - name: 🎈 Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@1.5

      - name: Deploy app to Fly.io
        id: deploy
        run: |
          flyctl deploy --remote-only -c apps/app/fly.toml \
            --build-secret DATABASE_CONN_TYPE=${{ secrets.DATABASE_CONN_TYPE }} \
            --build-secret DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-secret DATABASE_AUTH_TOKEN=${{ secrets.DATABASE_AUTH_TOKEN }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
