# name: "@tau/app Preview Deployment sync"
# on:
#   pull_request:
#       types: [synchronize]

# env:
#   FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
#   FLY_REGION: otp
#   FLY_ORG: personal
#   TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
#   TURBO_TEAM: ${{ vars.TURBO_TEAM }}

# jobs:
#   sync-preview:
#     runs-on: ubuntu-latest

#     outputs:
#       url: ${{ steps.deploy.outputs.url }}

#     concurrency:
#       group: pr-${{ github.event.number }}

#     environment:
#       name: pr-${{ github.event.number }}
#       url: ${{ steps.deploy.outputs.url }}

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 2

#       - name: Deploy PR app to Fly.io
#         id: deploy
#         uses: superfly/fly-pr-review-apps@1.3.0
#         with:
#           launch_options: "--build-arg TURBO_TEAM=${{ env.TURBO_TEAM }} --build-secret TURBO_TOKEN=${{ env.TURBO_TOKEN }}"
#           config: apps/app/fly.toml
