name: "@tau/app Preview Deployment clean"
on:
  pull_request:
    types: [closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  delete-preview:
    runs-on: ubuntu-latest

    concurrency:
      group: pr-${{ github.event.number }}

    environment: Preview

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get git branch name
        id: branch-name
        uses: tj-actions/branch-names@v8

      - name: Get database name
        id: db-name
        run: |
          BRANCH_NAME=$(echo "${{ steps.branch-name.outputs.current_branch }}" | tr -cd '[:alnum:]' | sed 's/./\L&/g' | cut -c 1-32)
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Deploy PR app to Fly.io
        id: deploy
        uses: superfly/fly-pr-review-apps@1.5.0
        with:
          config: apps/app/fly.toml

      - name: Delete Database
        id: delete-db
        uses: ./.github/actions/remove-preview-db
        with:
          api_token: ${{ secrets.TURSO_API_TOKEN }}
          organization_name: ${{ secrets.TURSO_ORGANIZATION_NAME }}
          database_name: ${{ steps.db-name.outputs.branch_name }}
